### ISSUE TITLE
Missing implementation in post.hbs 

### ISSUE THREAD

**Issue by mansona** [TryGhost/Starter#2]
In `post.hbs` it has the following comment: 

```handlebars
{{!-- There are two options for how we display the byline/author-info.
        If the post has more than one author, we load a specific template
        from includes/byline-multiple.hbs, otherwise, we just use the
        default byline. --}}
```
but it doesn't actually show any implementation for either byline types 🤔 it feels like there is something missing here but I'm not sure if I'm missing something

https://github.com/TryGhost/Starter/blob/master/post.hbs#L35

**Comment by kevinansfield** [comment]
It looks like the comment was left in when copying from Casper https://github.com/TryGhost/Casper/blob/master/post.hbs#L65:L74.

I don’t know if the byline being left out was intentional (@JohnONolan?) but you should be able to get an idea from Casper for how to extend the starter theme for your needs.

**Comment by mansona** [comment]
So yea I'm in the process of updating https://github.com/empress/create-empress-blog-template and "resyncing" it off this Ghost starter 👍 

I've recently implemented byline stuff for the casper resync here: https://github.com/empress/empress-blog-casper-template/blob/master/app/templates/post.hbs#L57 but that is using "components" in place of partials (partials is how casper does it)

I'm wondering if we ought to include a basic example of the two byline types in the starter template? 🤔 it feels like a bit of an inconsistency if we don't because the `{{navigation}}` helper has a "fallback implementation" https://docs.ghost.org/api/handlebars-themes/helpers/navigation/#default-template
