### ISSUE TITLE
build zip upload fail

### ISSUE THREAD

**Issue by SunSeekerX** [TryGhost/Starter#29]
![image](https://user-images.githubusercontent.com/48562733/83370782-f705ff80-a3f2-11ea-8ed9-874667df366d.png)

I clone this git repo，then install the dependencies and upload the ghost-starter-theme. i got an error.
here are the admin upload api  response

```json
{
    "errors":[
        {
            "message":"Failed to read zip file",
            "context":"ghost-starter-theme.zip",
            "type":"ValidationError",
            "details":"EACCES: permission denied, mkdir '/tmp/f60b92fb-9429-4733-941b-ef3990669e67/assets/built/'",
            "property":null,
            "help":"Your zip file might be corrupted, try unzipping and zipping again.",
            "code":null,
            "id":"bea48a00-a3af-11ea-87b7-f503e87db928"
        }
    ]
}
```

**Comment by SunSeekerX** [comment]
My ghost version is 3.17.0

**Comment by jloh** [comment]
Hey @SunSeekerX. This isn't an issue with the theme but an issue with your Ghost install. It cannot create folders in `/tmp/` for some reason, maybe the user Ghost is running as doesn't have permission?

Going to close this issue, if you need further help checkout the [help category](https://forum.ghost.org/c/help/6) on our forums or if you're a Ghost(Pro) user please reach out to support!

**Comment by SunSeekerX** [comment]
If I didn't use gulp-zip packaging, I wouldn't have this problem packaging zip with my own software.

**Comment by jloh** [comment]
Hey @SunSeekerX so you're saying when you zip the build up manually your Ghost instance doesn't throw an error? Only when using `yarn zip`?

**Comment by SunSeekerX** [comment]
> Hey @SunSeekerX so you're saying when you zip the build up manually your Ghost instance doesn't throw an error? Only when using `yarn zip`?

Yes,it just show up in a production environment. When I uploaded it to the local install ghost environment, it worked fine.

**Comment by JohnONolan** [comment]
Related https://github.com/TryGhost/Casper/issues/713 / https://github.com/TryGhost/Casper/pull/714

@daniellockyer Could you take a look at this?

**Comment by ErisDS** [comment]
This was fixed upstream in gulp-zip, closed by https://github.com/TryGhost/Starter/pull/32
