### ISSUE TITLE
Bookmarks have stretched thumbnails in Safari

### ISSUE THREAD

**Issue by steakscience** [TryGhost/Starter#40]
In other browsers:

<img width="942" alt="image" src="https://user-images.githubusercontent.com/2727095/101420864-aa612b00-3925-11eb-941d-ee57991dd16e.png">

In Safari:

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/2727095/101420818-93bad400-3925-11eb-8838-dc5fc81e4315.png">

**Comment by steakscience** [comment]
There is a "fix" in Casper, which drops flexbox and avoids this issue in Safari altogether. I can copy it over.

**Comment by minimaluminium** [comment]
Fixed in https://github.com/TryGhost/Starter/commit/ddafb593da8ce3e69fa19c6f817bb5167bd369b9.
