### ISSUE TITLE
The engine "ghost" appears to be invalid

### ISSUE THREAD

**Issue by mbrovko** [TryGhost/Starter#5]
<img width="682" alt="Screenshot 2019-08-31 at 21 36 24" src="https://user-images.githubusercontent.com/4989165/64067818-77ff5300-cc37-11e9-9014-a72b407c3d86.png">

Getting these warnings during theme installation. First time using Ghost.
Is there anything wrong with how the starter theme is configured?

Steps to reproduce:

- Install the latest Ghost
- Copy the starter theme into the project
- Run `yarn install`

**Comment by kevinansfield** [comment]
@mbrovko this is expected, in general all "warning" lines can be ignored 🙂 In future if you need any help/support please use [our forum](https://forum.ghost.org).
