### ISSUE TITLE
Error while executing yarn dev

### ISSUE THREAD

**Issue by singhs020** [TryGhost/Starter#51]
Hey Team,

I have received following error while trying to run the dev server on my local machine.

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /beeper/index.js
require() of ES modules is not supported.
require() of /beeper/index.js from //gulpfile.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/beeper/package.json.`

Looks like the beeper module used in gulpfile is converted to esm module and the file is no longer able to require it.

**Comment by madebyais** [comment]
Hi team,

Is there any workaround for this?

Thanks!

**Comment by singhs020** [comment]
hey @madebyais ,
personally I have removed it from the gulpfile. It is only used in the handle error function. if you still want to use it, then you have to import the module asynchronously. The repo is in commonjs and cannot require an esm module by default. 

```javascript
var beeper;

(async () => {
  const {"default": func} = await import('beeper');
  beeper = func;
})();
```

This should load the module in the current file and allow you to use it.

**Comment by fauzan121002** [comment]
![Capture](https://user-images.githubusercontent.com/50759463/118848360-e2b75d00-b8f8-11eb-9107-96e1b7eaf722.PNG)

Same here

node 14.17.0

**Comment by fauzan121002** [comment]
Sindre was decide to fully migrated to `ESM Modules`
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by minimaluminium** [comment]
Hey everyone, this was fixed in https://github.com/TryGhost/Starter/commit/75d65849b8a79f1cdd913d0b60389f33eefee270. Update your repo, install the dependencies again, and all should be good.
