### ISSUE TITLE
gscan for Ghost 5.0 raises error for signup page - no support for tiers

### ISSUE THREAD

**Issue by JBYoshi** [TryGhost/Starter#54]
When running the latest gscan for Ghost 5.0 compatibility on the current version of the theme, it raises the error "Replace `{{@price.monthly}}` and `{{@price.yearly}}` with `{{#get "tiers"}}` and `{{monthly_price}}` or `{{yearly_price}}`". It looks like the members pages need to be updated for the new tiers feature, or removed (the only official theme that uses those pages is [Pico](https://github.com/TryGhost/Pico)).

**Comment by ronaldlangeveld** [comment]
I made these changes last night and GScan / Theme uploaded successfully. 

https://github.com/ronaldlangeveld/Starter/blob/6530525406813f2b639ea1c6f4476f229bf93192/members/signup.hbs

It's a bad commit though, will have to clean up a bit before submitting for PR.

**Comment by minimaluminium** [comment]
Merged #55. Thanks @ronaldlangeveld!
