### ISSUE TITLE
Incomplete Documentation on Local Development

### ISSUE THREAD

**Issue by ChrisCates** [TryGhost/Starter#59]
The documentation needs to also describe how to symlink for local development.
Adding some markdown to explain how you can do live reload development would be great.

The following should be more than enough for any new comer.

```bash
# Setup your theme
git clone https://github.com/TryGhost/Starter my-theme
cd my-theme
yarn

# Now setup a local ghost instance
cd ..
mkdir ghost-dev
cd ghost-dev
ghost install local

# Link my theme to ghost dev instance
cd content/themes
ln -s ~/my-theme .

# Restart ghost and start developing
cd ../..
ghost restart

# Now head on over to http://localhost:2368/ghost/
# You should now be able to see your theme in the theme directory.
```

**Comment by royalfig** [comment]
We just updated our Starter theme to a new build process, and I included more info about symlinking. Thanks! We also updated how the livereload server works, so you should be able to use it out of the box without issue 😄

**Comment by ChrisCates** [comment]
Awesome! Glad to hear brother!
Cheers
