### ISSUE TITLE
How to add Tailwindcss to the Starter theme

### ISSUE THREAD

**Issue by royalfig** [TryGhost/Starter#61]
Hello @royalfig I am looking into using TailwindCSS for my custom Ghost theme. I came across [this](https://forum.ghost.org/t/a-guide-for-developing-ghost-themes-with-tailwindcss/35680) post on the Ghost Forum. However, it is for the Gulp "configuration". If you have any pointers/ideas on how to get TailwindCSS implemented with Rollup I would appreciate it (I did try [this](https://forum.ghost.org/t/a-guide-for-developing-ghost-themes-with-tailwindcss/35680) plugin but it doesn't seem to be working). Cheer!

_Originally posted by @Isaac-Tait in https://github.com/TryGhost/Starter/issues/60#issuecomment-1513963799_

**Comment by royalfig** [comment]
To add Tailwind to the Starter theme:

## Install the dependencies
```bash
npm install -D tailwindcss autoprefixer
```

## Create a Tailwind config
```bash
npx tailwindcss init
```
## Update the Tailwind config
```javascript
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {},
  },
  plugins: [],
  content: [
    "/*.hbs",
    "./**/*.hbs",
  ]
}

```
## Update CSS
Include Tailwind base styles
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

## Update Rollup config
```javascript
// Update the imports
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';

// Update the postcss config
postcss({
            extract: true,
            plugins: [
                tailwindcss,
                autoprefixer
            ]
}),
```

That should do it.

**Comment by Isaac-Tait** [comment]
I am running into a bit of a speed bump with this process. So far I have done the following:

`cd` into an empty directory then ran the command `ghost install local` then `cd content/themes` followed by `git clone https://github.com/TryGhost/Starter.git ghost-with-tailwind` then `cd ghost-with-tailwind` and `yarn install` Pretty basic/straightforward. Then I implement your steps but when I run `ghost restart` I do not see any changes to the page on localhost when I change/update `index.hbs`. It seems local host is grabbing the content from `casper` and isn't running from the newly created `ghost-with-tailwind` directory. What am I missing? 

[Here](https://s.tape.sh/3zHUvsYE) is a video showing what I am seeing.

**Comment by royalfig** [comment]
Have you activated the theme from Ghost Admin? This isn't the best place for support, so if you still have trouble, I recommend coming over to the official [Ghost Forum](https://forum.ghost.org). We'll get you sorted!

**Comment by Isaac-Tait** [comment]
Thanks @royalfig for the guidance, I appreciate it. I will reach out to support

**Comment by rosu-catalin** [comment]
After doing the steps above, I get this annoying error. Do you have any idea why I get this error?


[!] (plugin postcss) Error: ENOENT: no such file or directory, stat 'C:/author.hbs'
assets/css/index.css
    at Object.statSync (node:fs:1596:3)
    at resolveChangedFiles (C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\tailwindcss\lib\lib\content.js:166:36)
    at resolvedChangedContent (C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\tailwindcss\lib\lib\content.js:138:42)
    at C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:130:101
    at C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\tailwindcss\lib\processTailwindFeatures.js:46:11
    at plugins (C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\tailwindcss\lib\plugin.js:38:63)
    at LazyResult.runOnRoot (C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\postcss\lib\lazy-result.js:339:16)
    at LazyResult.runAsync (C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\postcss\lib\lazy-result.js:393:26)
    at LazyResult.async (C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\postcss\lib\lazy-result.js:221:30)
    at LazyResult.then (C:\Users\zonet\Desktop\Ghost Theme Recode\content\themes\deluxe_ghost\node_modules\postcss\lib\lazy-result.js:206:17)

**Comment by rosu-catalin** [comment]
Tailwind is not working with livereload I guess

**Comment by royalfig** [comment]
@rosu-catalin What are you experiencing exactly?

This might be a bug with the postcss plugin. I'll do some more investigation and follow up.

**Comment by rosu-catalin** [comment]
While I'm using rollup for live reload with Tailwind, it's kind of blocked in a reload loop, as you can see in the video below.

[https://www.youtube.com/watch?v=O168MB8iVt8](url)

**Comment by royalfig** [comment]
I believe this is caused by a bug in the `postcss` plugin we're using: https://github.com/egoist/rollup-plugin-postcss/issues/414

 I'm trying to see if there's a workaround.

**Comment by royalfig** [comment]
After some experimentation, here's what I found to be the best way to use Tailwind here (given the bug in the postcss plugin). 

The solution here is to use Tailwind's CLI tool alongside Rollup. Where Tailwind processes the CSS from HBS files, Rollup handles all the JS. 

1. `npm i -D concurrently tailwindcss`
2. Remove the CSS import from `assets/js/index.js`
3. Update `assets/css/index.css` with the standard Tailwind directives:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
4. Remove the `postcss` sections from `rollup.config.js`
5. Update the `dev` and `build` scripts in `package.json`:
```json
 "dev": "concurrently \"rollup -c --environment BUILD:development -w\" \"npx tailwindcss -i ./assets/css/index.css -o ./assets/built/index.css --watch\" ",
"build": "rollup -c --environment BUILD:production && npx tailwindcss -i ./assets/css/index.css -o ./assets/built/index.css --minify",
```
6. Remove and/or uninstall unused CSS/JS/packages

**Comment by rosu-catalin** [comment]
Works now! Thanks a lot

**Comment by BondAnthony** [comment]
Thank you! This helped me get started and I was able to keep the existing styles by importing the tailwindcss delectations from the node_modules directory. This allows you to keep the postcss configurations. https://tailwindcss.com/docs/using-with-preprocessors 

example
```
@import "tailwindcss/base";
@import "./custom-base-styles.css";

@import "tailwindcss/components";
@import "./custom-components.css";

@import "tailwindcss/utilities";
@import "./custom-utilities.css";
```
