### ISSUE TITLE
Is there a way to apply the frontend theme to admin editor?

### ISSUE THREAD

**Issue by Ravim-addweb** [TryGhost/Starter#62]
I am inclined towards providing WYSIWYG kinda visual look & feel to my content editors. Therefore, for example, if they're managing the homepage, they would be getting exact idea about how the frontend is going to look like.

Is there any way, I can load the frontend assets such as styling, icons, themes, fonts etc to the Ghost CMS admin editor?

**Comment by royalfig** [comment]
The Admin styling isn't open to theming. Given its complexity, this is by design.

**Comment by Ravim-addweb** [comment]
Thanks @royalfig for prompt response. Just one question, is it possible to create custom card/block inside the admin editor? Please check attached image for reference. Basically I would love to create several blocks here, each block would render a section which will help content editor to input the data on specific places of that content (be it text or image/video). Appreciate your help, thanks!

![Clipboard - April 21, 2023 6 18 PM](https://user-images.githubusercontent.com/41608861/233642672-85280013-cbd7-403e-ab05-4e693325546b.png)

**Comment by royalfig** [comment]
That isn't possible. I'd recommend you check out the docs (https://ghost.org/docs/) or head on over to our Forum for additional support: https://forum.ghost.org. There are lots of community members available to help you out!

**Comment by Ravim-addweb** [comment]
Thanks @royalfig appreciate your help!
