### ISSUE TITLE
Starter theme fails gscan

### ISSUE THREAD

**Issue by jeseekia** [TryGhost/Starter#87]
After creating a repository using the Starter template and going through the installation instructions, when finally running ```npm run test``` the following error is given: 

> Your theme has 1 error!
> ----
> 
> Errors
> ------
> Important to fix, functionality may be degraded.
> 
> - Error: Not all page features are being used
> Affected Files: page.hbs

When testing with the [browser gscan tool](https://gscan.ghost.org/) the following details are provided:
> This error only applies to pages created with the Beta editor. Some page features used by Ghost via the {{@page}} global are not implemented in this theme. Find more information about the {{@page}} global [here](https://ghost.org/docs/themes/helpers/page/).
> 
> Affected files:
> page.hbs: @page.show_title_and_feature_image is not used

Looking into the {{@page}} documentation, I found more details to resolve this issue in my install by incorporating this helper into page.hbs
```
{{#match @page.show_title_and_feature_image}}
...content...
{{/match}}
```

> @page.show_title_and_feature_image - true (default) or false value from Ghost Editor
> This toggle, only available for pages, lets users hide a page’s title and feature image to create pages that look radically different than posts (for example, full-width headers, CTAs, and landing pages).
> 
> This setting is only available when using the [new Beta editor](https://ghost.org/changelog/editor-beta/). However, since the @page.show_title_and_feature_image is always present and defaults to true, supporting this feature in your theme won’t break anything for anyone using the old editor.
> 
> Using the @page object is not backward-compatible with earlier versions of Ghost: once implemented the theme will only be compatible with Ghost 5.54.1 or later.

Is this a known issue? I just created a theme from the template today 10/31/23. When attempting to upload the theme without a fix the following error is given in the Ghost admin dashboard: 
<img width="812" alt="Screenshot 2023-10-31 at 2 52 49 PM" src="https://github.com/TryGhost/Starter/assets/8432802/085700d9-8b11-487c-83e0-a055894603ad">

I'm happy to submit a PR for a fix, but wanted to raise this issue first.

**Comment by royalfig** [comment]
Thanks for submitting that great report. While a theme will still be usable despite this error, you're right that the theme should be updated to use the new `@page.show_title_and_feature_image` helper. 

We'd welcome a PR to add the helper which would require an update to the `page.hbs` template and possible CSS to support the helper.

**Comment by minimaluminium** [comment]
@jeseekia This should now be fixed with the help of https://github.com/TryGhost/Starter/pull/88.
